DATA Pre-processing

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf


In [ ]:
tf.__version__

'2.3.0'

In [ ]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [ ]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le =LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [ ]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.3, random_state = 42)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)


In [ ]:
ann = tf.keras.models.Sequential()


In [ ]:
ann.add(tf.keras.layers.Dense(units=7,activation = 'relu'))

In [ ]:
ann.add(tf.keras.layers.Dense(units=7,activation='relu'))

In [ ]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [ ]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
ann.fit(X_train,y_train,batch_size=32,epochs=70)

Epoch 1/70
219/219 [==============================] - 0s 1ms/step - loss: 0.3310 - accuracy: 0.8656
Epoch 2/70
219/219 [==============================] - 0s 1ms/step - loss: 0.3305 - accuracy: 0.8640
Epoch 3/70
219/219 [==============================] - 0s 1ms/step - loss: 0.3307 - accuracy: 0.8651
Epoch 4/70
219/219 [==============================] - 0s 1ms/step - loss: 0.3305 - accuracy: 0.8646
Epoch 5/70
219/219 [==============================] - 0s 1ms/step - loss: 0.3305 - accuracy: 0.8653
Epoch 6/70
219/219 [==============================] - 0s 1ms/step - loss: 0.3304 - accuracy: 0.8659
Epoch 7/70
219/219 [==============================] - 0s 1ms/step - loss: 0.3304 - accuracy: 0.8644
Epoch 8/70
219/219 [==============================] - 0s 1ms/step - loss: 0.3300 - accuracy: 0.8666
Epoch 9/70
219/219 [==============================] - 0s 1ms/step - loss: 0.3307 - accuracy: 0.8647
Epoch 10/70
219/219 [==============================] - 0s 1ms/step - loss: 0.3300 - accuracy: 0.8646

Predicting the Test results

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred >0.6)


In [ ]:

print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[2365   51]
 [ 355  229]]


0.8646666666666667